### PR TITLE
Add Dockerfile including preCICE installation

### PR DESCRIPTION
**Pull request by BenjaminRueth**
This PR contributes a Dockerfile for installing preCICE on top of `ci-ubuntu-2004`.

### CODE REVIEW

**Comment by BenjaminRueth** [comment]
Important note: `test_base` was failing for me when I tried to build the image. I could not find an obvious reason, but will try to investigate. However, I did not run into further problems downstream when using this image (see https://github.com/precice/python-bindings/pull/67).

**Comment by BenjaminRueth** [comment]
7dec86f  fixes the problem with the tests by using a non-root user. Ready for review.

**Comment by fsimonis** [comment]
What is the use-case for this image?

As we discussed, there will soon be a preCICE docker image which will be updated with every release.
Doesn't it fulfil your requirements?

**Comment by BenjaminRueth** [comment]
### on the use-case

The main use-case is the CI pipeline for the python-bindings. See https://github.com/precice/python-bindings/pull/67.

### on the requirements

I first tried to use https://github.com/precice/systemtests/blob/develop/precice/Dockerfile.Ubuntu2004.home for my test. However, here, `curl` and `python3` was missing which is provided with https://github.com/precice/ci-images/blob/master/ci-ubuntu-2004.dockerfile. That's the main reason why I decided to create a new image based on `ci-ubuntu-2004`.

**Comment by fsimonis** [comment]
This PR is superseded by https://github.com/precice/precice/pull/910

**Pull request closed without merging**
